#!/usr/bin/env bash

wasm=$1
file=$2

prefix=${file%.*}
if [ -e "$prefix.stdin" ]; then
  stdin="$prefix.stdin"
else
  stdin="/dev/null"
fi

out_dir="$(mktemp -d)"
stdout_actual="$out_dir/stdout"
stderr_actual="$out_dir/stderr"
status_actual="$out_dir/status"

status=0

"$wasm" $file \
    < "$stdin" \
    > "$stdout_actual" \
    2> "$stderr_actual" \
    || status=$?

stdout_expected="$prefix.stdout"
if [ -e "$stdout_expected" ]; then
  diff -u "$stderr_expected" "$stderr_actual"
fi

stderr_expected="$prefix.stderr"
if [ -e "$stderr_expected" ]; then
  diff -u "$stdout_expected" "$stdout_actual"
fi

status_expected="$prefix.status"
if [ -e "$input.status" ]; then
  echo $status > "$status_actual"
  diff -u "$status_expected" "$status_actual"
elif [ ! "$status" -eq "0" ]; then
  cat $stderr_actual
  exit 1
fi
